### ISSUE TITLE
v0.31 release page on this repository has no instruction or a link to a firmware installation guide

### ISSUE THREAD

**Issue by Gerriko** [analogdevicesinc/m2k-fw#13]
I've only just recently purchased an ADALM2000 module.

The very first instruction shown on the webpage you load via the ADALM2000 media folder is "Upgrade your firmware".

This sends you straight to the release page of this repository, which provides a very basic change log (inside Summary section) and not much else. There is not even a readme file as part of the Assets or a readme file in any of the zip files.

I wish to get started quickly but having gone to the online wiki page, I could not find an obvious link or section that provides instruction.

So please can someone add a link on the release page that redirects to the correct details on the wiki and/or add in a readme file.

Thanks

**Comment by Gerriko** [comment]
I have finally found the right page (inserting here for others as interim fallback): https://wiki.analog.com/university/tools/m2k/common/firmware

**Comment by mhennerich** [comment]
ok - let's close this then
