### ISSUE TITLE
Easy to lose connection

### ISSUE THREAD

**Issue by SunnyTian** [analogdevicesinc/m2k-fw#14]
Hi,
I'm using the network analyzer module in scopy,but it is easy to lose connection after grabbing data for several times.
Please tell me the reason of losing connection or how to Positioning reasons,and how to fix this problem.
Thanks!
Here is the information of m2k module:
![20231226-142155](https://github.com/analogdevicesinc/m2k-fw/assets/17664209/4e00a4e8-2103-4674-a973-569819e06e4a)

**Comment by mhennerich** [comment]
Wondering if this is more a Scopy issue?
Does Scopy exit? Can you reconnect using Scopy?

**Comment by SunnyTian** [comment]
> Wondering if this is more a Scopy issue?
> Does Scopy exit? 
I didn't exit scopy.
Can you reconnect using Scopy?
This time I can't find M2K devices,the only solution is unplug and then plug the usb connector.
Seems like the libiio driver but I'm not sure.

**Comment by mhennerich** [comment]
Can't replicate on my side.
