### ISSUE TITLE
Fix cross compiler prefix environment variable

### ISSUE THREAD

**Issue by cajt** [analogdevicesinc/m2k-fw#2]
In README.md 

> export CROSS_COMPILE=arm-xilinx-linux-gnueabi- 

should be:

> export CROSS_COMPILE=arm-linux-gnueabihf-

(like it is in https://wiki.analog.com/university/tools/pluto/building_the_image )

**Comment by mhennerich** [comment]
Should be fixed now - thanks for reporting.
