### ISSUE TITLE
libssl1.0-dev is not available

### ISSUE THREAD

**Issue by bobyang6** [analogdevicesinc/m2k-fw#6]
Command is 
$ sudo apt-get install dfu-util u-boot-tools device-tree-compiler libssl1.0-dev mtools
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package
This may mean that the package is missing, has been obsoleted, or is only available from another source

For now I delete the '1.0' in libssl1.0-dev and continue. But this is a problem.

**Comment by mhennerich** [comment]
Availability of this package depends on your distro and version.
If your build succeed than all is good.
If you need further assistance please specify your build environment and reopen this issue.
