### ISSUE TITLE
Distribution toolchains are unsuitable for use by Buildroot,

### ISSUE THREAD

**Issue by bobyang6** [analogdevicesinc/m2k-fw#8]
Distribution toolchains are unsuitable for use by Buildroot,
as they were configured in a way that makes them non-relocatable,
and contain a lot of pre-built libraries that would conflict with
the ones Buildroot wants to build.
make[2]:***[package/pkg-generic.mk:240: /home/vivado/m2k-fw/buildroot/output/build/toolchain-external-custom/.stamp_configured] Error 1
make[1]: *** [Makefile:84: _all]Error 2
make[1]: Leaving directory '/home/vivado/m2k-fw/buildroot'
make: *** [Makefile:104: buildroot/output/images/rootfs.cpio.gz] Error 2

Ubuntu version 20.04LTS
Vivado version 2021.1

**Comment by mhennerich** [comment]
This was addressed with the patch
https://github.com/analogdevicesinc/buildroot/commit/e5b7b352c3f817cc6c20e6e14509106d4df663bb

Let's close this
