### ISSUE TITLE
ADALM2000 dac push function cause reset

### ISSUE THREAD

**Issue by xingzhan2012** [analogdevicesinc/m2k-fw#9]
I use ADALM2000 to drive galvanometer, it seems that the dac will output zero value, then output what I pushed value after I call push function to send some value to it's DAC output-channel. So, it will cause galvanometer shaking. Another issue is that push function of analog-out-put is too slow in python program. I wander that is there any way to avoid this? Maybe you can repair that problem. thanks!

**Comment by mhennerich** [comment]
The upcoming FW release will support this feature: 

iio: frequency: m2k-dac: Add support for raw vaules
https://github.com/analogdevicesinc/linux/pull/2355/commits/f64f6dd9bb8e2eeaf21191d729d5e3fe5c4893e2
 
Maybe this helps...
